---
title: "Bank_Decision_tree"
author: "YI-LING HUANG"
date: "4/18/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ROSE)
library(rpart)
library(dplyr)
library(rattle)
library(caret)
library(C50)
library(dplyr)
```

# import dataset
```{r}
a <- read.csv("bank.csv")
```

# check missing value and label's distribution
```{r}
length(which(!complete.cases(a)))
summary(a$y)
```

# split data into train and test set
```{r}
n <- nrow(a)
n_train <- round(.6*n)
set.seed(456)
train_index <- sample(1:n, n_train)
train <- a[train_index,]
test <- a[-train_index,]
```

# balance labels on training set
```{r}
set.seed(1)
r = ovun.sample(y~., data = train, method="both", seed = 2)$data
```

# fit data into decision tree
```{r}
fit <- C5.0(y~., data = r, method = 'class', trials = 20, rules = TRUE)
```

```{r}
summary(fit)
```


# show important variables
```{r}
C5imp(fit, metric = "usage")
```

# fit model to test set
```{r}
tree_pred <- predict(fit, test, type = "class")

```

# performance of model
```{r}
confusionMatrix(data = tree_pred,
                reference = test$y)
```

# plot roc curve and list auc
```{r}
d = roc.curve(test$y,tree_pred)
d$auc
```


#-----------------------------------------------------------------------------------
# cross validation and parameter tuning
```{r}
X = a %>%
    select(-y)
y= a$y
```

```{r}
c = trainControl(method = "repeatedcv",
                 number = 5,
                 repeats = 5,
                 p = 0.6,
                 sampling = "rose")
model = train(x = X, y = y, trControl = c, method="C5.0",verbose=FALSE )
```

```{r}
model
```

```{r}
plot(model)
```

